### ISSUE TITLE
this happens no mater what i try to do

### ISSUE THREAD

**Issue by Rubber4** [SilentChaos512/SilentLib#10]
ok so when ever i run the game this pops up: The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.ClassCastException: net.silentchaos512.lib.item.ItemGuideBookSL cannot be cast to net.silentchaos512.lib.registry.IRegistryObject

**Comment by SilentChaos512** [comment]
Version information would have been helpful, but that sounds like you need to update Silent's Gems.
(edit) Yes, looks just like SilentChaos512/SilentGems#323

**Comment by Rubber4** [comment]
oh ok i'm stupid. that helped a lot. thank you

**Comment by SilentChaos512** [comment]
No problem. It's a bit messy right now with all the alpha and beta builds.
