### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by zadzial** [SilentChaos512/SilentLib#12]
This crash seems to be happening while the Forge screen is  working and using older versions does not help - they're not compatible with recent Silent mods or they also crash. 

Thanks

[crash-2018-09-28_06.52.10-client.txt](https://github.com/SilentChaos512/SilentLib/files/2425892/crash-2018-09-28_06.52.10-client.txt)

**Comment by SilentChaos512** [comment]
Update Extra Parts to latest (1.4.5). I'm marking it as a release build now.

**Comment by zadzial** [comment]
Awesome! Thankyou!
