### ISSUE TITLE
issue with class registry in latest version of silentlib

### ISSUE THREAD

**Issue by LordDecay26** [SilentChaos512/SilentLib#13]
pastebin of the crashlog can be found, here:

https://pastebin.com/6TAxS7Cn

**Comment by SilentChaos512** [comment]
Try updating Extended Days to the latest version.

**Comment by ThelianTech** [comment]
Im Having the same issue and I do have the latest ExtendedDays-1.12.2-0.2.8-26.jar with SilentLib-1.12.2-3.0.9-159.jar. here is my Crashlog: https://pastebin.com/9J3qfFKX

**Comment by SilentChaos512** [comment]
@EmberFlash Update Scaling Health to a more recent version (either 1.3.30 or 1.3.31)
