### ISSUE TITLE
silent mods be sending packets before Forge's modlist sync packet[1.15.2]

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/SilentLib#20]
forge:1.15.2-31.1.27

server latest
https://gist.githubusercontent.com/SDUBZ/109b711c4d3ed0c7f54fdf6ccb280d8e/raw/0970bb7abf9d571a541bd85cd0336b5a1903d296/latest.log

debug latest
https://gist.githubusercontent.com/SDUBZ/7fe8fa77753c119796eb1121cf2e7649/raw/b53ed60b3cf756f94dc9483ba1cfd3d15cebf046/debug.log

**Comment by SilentChaos512** [comment]
What part of the log files indicate this is happening? Is it a serious problem?

**Comment by SDUBZ** [comment]
yes its a very serious problem are you part of the forge discord, one of the mods in forge dc said this http://puu.sh/FpoEu/1abea7f735.png

**Comment by SilentChaos512** [comment]
OK, could you tell me more about the symptoms? Any clues as to what should be done? I'm not sure what packets I could be sending before mod list sync. Do you know which mod(s) specifically is/are the cause?

**Comment by SDUBZ** [comment]
im not but the moderator daemon told me about it on the forge discord if you dont know how to do this maybe you can ask here https://discord.gg/UvedJ9m for help
