### ISSUE TITLE
Cant build project

### ISSUE THREAD

**Issue by GiaNTizmO** [SilentChaos512/SilentLib#23]
``Build file 'C:\Users\Gamania\Desktop\SilentLib-1.12\build.gradle' line: 181

Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':extraLibs'.
   > Could not find any matches for net.silentchaos512:silent-utils:1.+ as no versions of net.silentchaos512:silent-utils are available.
     Searched in the following locations:
         https://files.minecraftforge.net/maven/net/silentchaos512/silent-utils/maven-metadata.xml
         https://files.minecraftforge.net/maven/net/silentchaos512/silent-utils/
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/maven-metadata.xml
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/
         https://libraries.minecraft.net/net/silentchaos512/silent-utils/maven-metadata.xml
         https://libraries.minecraft.net/net/silentchaos512/silent-utils/
         file:/C:/Users/Gamania/Desktop/SilentLib-1.12/repo/
         file:/C:/Users/Gamania/.m2/repository/net/silentchaos512/silent-utils/maven-metadata.xml
         file:/C:/Users/Gamania/.m2/repository/net/silentchaos512/silent-utils/
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/maven-metadata.xml
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/
         https://jcenter.bintray.com/net/silentchaos512/silent-utils/maven-metadata.xml
         https://jcenter.bintray.com/net/silentchaos512/silent-utils/
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/maven-metadata.xml
         https://repo.maven.apache.org/maven2/net/silentchaos512/silent-utils/
         http://dvs1.progwml6.com/files/maven/net/silentchaos512/silent-utils/maven-metadata.xml
         http://dvs1.progwml6.com/files/maven/net/silentchaos512/silent-utils/
         file:/C:/Users/Gamania/Desktop/SilentLib-1.12/modmaven.k-4u.nl/net/silentchaos512/silent-utils/maven-metadata.xml
         file:/C:/Users/Gamania/Desktop/SilentLib-1.12/modmaven.k-4u.nl/net/silentchaos512/silent-utils/
         file:/C:/Users/Gamania/.gradle/caches/minecraft/deobfedDeps/net/silentchaos512/silent-utils/maven-metadata.xml
         file:/C:/Users/Gamania/.gradle/caches/minecraft/deobfedDeps/net/silentchaos512/silent-utils/
         file:/C:/Users/Gamania/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2807/stable/39/
     Required by:
         project :
``

**Comment by GiaNTizmO** [comment]
UPD: I found new Maven repo, its helped me:

`    maven { // Silent-utils alternative repo
        name = "ModMaven"
        url = "https://dl.bintray.com/silentchaos512/silent-utils/"
    }
`

**Comment by SilentChaos512** [comment]
So, is this resolved?

**Comment by GiaNTizmO** [comment]
> So, is this resolved?

Yes!
