### ISSUE TITLE
Repairs costing only 1 resource

### ISSUE THREAD

**Issue by GigaAkuma** [SilentChaos512/SilentLib#24]
When trying to repair any armor piece created with silent gear, it only costs 1 resource of the same tier as the ones used to create the armor, so its possible to repair something made entirely out of diamonds or obsidian with just 1 emerald. And the cost of repairs doesn't increase on subsequent repairs.

forge 31.1.63 
tested with only silent gear and silent lib loaded

**Comment by SilentChaos512** [comment]
Please report this on the Silent Gear repo. Include all relevant mod
versions.
