### ISSUE TITLE
World corruption

### ISSUE THREAD

**Issue by 47delasPECIIKOMODO** [SilentChaos512/SilentLib#28]
After updated the mod i got my world corrupted, can't load my world
forge - 1.16.4-forge-35.1.36
[debug.log](https://github.com/SilentChaos512/SilentLib/files/5810523/debug.log)
[latest.log](https://github.com/SilentChaos512/SilentLib/files/5810524/latest.log)
![Untitled](https://user-images.githubusercontent.com/77338081/104495719-c5882000-55e0-11eb-83e2-0944a1018d11.png)

**Comment by SilentChaos512** [comment]
Does this happen to new worlds? Did you update any other mods at the same time? Have you tried rolling back your mod pack to an earlier version? I am not seeing anything to looks related to Silent Lib.

The last stacktrace I see mentions some kind of world generation error. The line above that in your debug.log, line 23247, is:

`[13Jan2021 20:46:24.058] [Render thread/DEBUG] [Dungeon Crawl/]: Generation Biome: jamd:mining`

I would try investigating that first.
