### ISSUE TITLE
New Lib file causing datapack error?

### ISSUE THREAD

**Issue by judicius** [SilentChaos512/SilentLib#30]
seems the update to Silent's Library has cause current datapacks to fail.
https://gist.github.com/judicius/8cae888e2f22f8efe411be2ae0e67bd9

Silent-lib: 4.10.0
Forge 36.1.32

**Comment by SilentChaos512** [comment]
Seems I will need to update some of my mods to official mappings as well
for them to work together. Not what I was expecting, but oh well. Just go
back to 4.9.x for now. Leave this issue open.
