### ISSUE TITLE
Please allow access to your mod for third party lanuchers.

### ISSUE THREAD

**Issue by blackd** [SilentChaos512/SilentLib#35]
With the new curseforge REST API rollout your mods are currently only accessible using the curseforge site and the curseforge app.

Could you please allow access for launchers like ATLauncher.

For more info https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

**Comment by SilentChaos512** [comment]
I decided to allow this. While I'm not happy about my mods being distributed outside Curseforge, I know that people will find away around it regardless. Just remember that I earn nothing for my hard work when you download outside of Curse.
