### ISSUE TITLE
Cant install SilentLib on aternos!

### ISSUE THREAD

**Issue by BlackWarrior2004** [SilentChaos512/SilentLib#36]
I can add your mod like Scaling health there but not the required dependency SilentLib on Aternos.org! The reason is in the screen shot! I am looking forward to your response, but please fix it, I really need this mod for my modpack
![image_2022-05-29_030520503](https://user-images.githubusercontent.com/83131147/170843560-8d01a7cf-7237-4492-9675-c1744e0d5139.png)

**Comment by SilentChaos512** [comment]
Why is downloading from Curse an issue?

**Comment by BlackWarrior2004** [comment]
> Why is downloading from Curse an issue?

I can download it from curse, but I want to play it with my friends on the server, so when trying to get it on the server, I can get the mods that depend on it, like Scaling health, but not this one

**Comment by ASGAMING009** [comment]
> Why is downloading from Curse an issue?

Im Here For the Same Reason But I didn't Make an issue.
So basically You cant upload your mods In aternos You have to add them from curseforge and The Author have to enable 3rd party distribution. 
Its my humble Request That You Should Turn on The 3rd party distribution so we can play on the server And enjoy Your mods. Thanks For All The Great Mods.

**Comment by ASGAMING009** [comment]
![Screenshot_2022-05-29-22-38-57-661_com android chrome](https://user-images.githubusercontent.com/68546736/170882767-00c0764d-9532-4610-adce-b93801539e58.png)
![Screenshot_2022-05-29-22-38-49-285_com android chrome](https://user-images.githubusercontent.com/68546736/170882772-f4282ee6-0bcd-47a7-a8a8-c5f8501acafe.png)

Many People Want This Mod In their server. Please Mate.

**Comment by ASGAMING009** [comment]
> Why is downloading from Curse an issue?

Please man its a genuine request!

**Comment by SilentChaos512** [comment]
I decided to allow this. While I'm not happy about my mods being distributed outside Curseforge, I know that people will find away around it regardless. Just remember that I earn nothing for my hard work when you download outside of Curse.

Related: #35

(edit) I should also note that I no longer maintain Scaling Health. I made no changes to its distribution settings.
