### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by s1mnbrgss** [SilentChaos512/SilentLib#43]
Just updated Minecraft to version 1.20.4 and trying to figure out which mod(s) are causing issues. Encountered this error: Silent Lib (silentlib) has failed to load correctly

java.lang.NoClassDefFoundError: net/minecraftforge/common/crafting/IIngredientSerializer

**Comment by SilentChaos512** [comment]
Silent Lib has been updated for 1.20.4 with NeoForge. But none of my other mods are updated as of yet.
