### ISSUE TITLE
Log Spam with Latest 1.12.1

### ISSUE THREAD

**Issue by TensorTime** [SilentChaos512/SilentLib#5]
Versions:
**Minecraft** 1.12.1
**Forge** 14.22.1.2484
**Silent Lib** 1.12-2.2.7-85
**Silent's Gems** 1.12-2.4.7-221

Spam starts during initial worldgen.  Check starting at time: [13:39:51]

--tensor

https://gist.github.com/TensorTime/9dee4f5a9061077c68234205916ab275

**Comment by TensorTime** [comment]
Spam starts during initial worldgen.  Sorry should have had that in the first post!

--tensor

**Comment by SilentChaos512** [comment]
Probably Gems. I did have a debug line on oregen, I guess I forgot to
remove it. Good news is it should only happen during terrain generation.
