### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentLib#7]
[18:16:38] [main/FATAL] [FML]: The mod scalinghealth (Scaling Health) requires mod versions [silentlib@[2.2.16,)] to be available

**Comment by SilentChaos512** [comment]
2.2.16 should be available, is it not?

**Comment by P3rf3ctXZer0** [comment]
Its not available.

**Comment by SilentChaos512** [comment]
https://minecraft.curseforge.com/projects/silent-lib/files/2511191

**Comment by P3rf3ctXZer0** [comment]
Oh well in that case its not working because I have that. Oh shit somehow I never updated silent lib I am so sorry bro :( I failed as a beta.
