### ISSUE TITLE
Crash - Dedicated Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentLib#8]
https://gist.github.com/P3rf3ctXZer0/2e337e4c0b2efb9c5ca5cdf1c6dd5ad5

**Comment by SilentChaos512** [comment]
Well, darn. That might require a Scaling Health update too. Give me about half an hour.

**Comment by SilentChaos512** [comment]
Review process on Curse is taking a while. I'll just link the files here for now:
[issue8-fix.zip](https://github.com/SilentChaos512/SilentLib/files/1846020/issue8-fix.zip)
